Seo updates
joshmobley/gopc pull request #1
Opened 2017-06-12 20:43 UTC by bkfrye

# Why
- Needed to correct some syntax for SEO optimization

# What Changed
- Replaced header logo with img tag instead of `<h1>` with background img
- Switched `<h2>` with `<h1>` on product pages
-- Should promote better rankings for products

2017-06-12 20:44 UTC, bkfrye commented
I only made CSS changes to the header logo, so it shouldn't change anything else on the site. Let me know if you see any issues that cascade down.

2017-06-14 12:27 UTC, joshmobley requested changes
Wondering about CSS specificity, take a look at my comment.

2017-06-14 12:27 UTC, joshmobley commented on wp-content/themes/great-outdoor/header.php
> +                <img src="<?php echo get_stylesheet_directory_uri() . '/assets/logo.png' ?>" alt="GOPC logo">
I'm wondering if we should use `.logo` or some other class here to add specificity to this particular image.  I can think of a few places in the mega-menus where images are being used, and `header img` would likely cascade down. Alternatively perhaps we just style it with `header > img`?

2017-06-14 17:15 UTC, bkfrye commented on wp-content/themes/great-outdoor/header.php
> +                <img src="<?php echo get_stylesheet_directory_uri() . '/assets/logo.png' ?>" alt="GOPC logo">
To keep things explicit, I just added an id to the image. It probably doesn't need to be nested like `header #masthead` but I went with it. Thanks for the feedback to help things move along more smoothly.

2017-06-14 17:24 UTC, joshmobley approved these changes
thanks!

2017-06-14 17:24 UTC, merged